# Generated by Django 5.2.7 on 2025-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
